### ISSUE TITLE
Asks for user input in non interactive enviroment

### ISSUE THREAD

**Issue by 1Mattchu** [mariusschueller/MATRIX#1]
Starting from line 8:

Change to:

```
def main():
    input_dir_path = os.getenv("STL_INPUT_DIR", "/app/stl_input")
    output_file = os.getenv("GCODE_OUTPUT_DIR", "/app/gcode_output")


    print(f"Using input directory: {input_dir_path}")
    print(f"Using output file: {output_file}")
    
    # rest of the schmoo

```

Keep those file directories as fallbacks, or if I just don't want to add in variables for it lol.

My change(just for my reference):

```
matrixapi:
    build: .
    environment:
      - STL_INPUT_DIR=/app/stl_input
      - GCODE_OUTPUT_DIR=/app/gcode_output
```
